server:
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    name: eventos
    username: sa
    password: password
    url: jdbc:h2:mem:eventos
    driverClassName: org.h2.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true # on/off swagger
    path: /doc/swagger-ui.html # ruta default: http://localhost:8080/swagger-ui/index.html

# springdoc.pathsToMatch = x/x, x/x